WebUILayer/Controllers/ContactInformationController.cs
using EntityLayer.Entity;
using EntityLayer.Modal;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUILayer.Controllers
{
    public class ContactInformationController : Controller
    {
        // GET: ContactInformation
        SystemContext db = new SystemContext();
        public ActionResult Index()
        {
            var contact = db.ContactInformations.Where(x => !x.DeletionStatüs).ToList();
            if (contact.Count != 0)
            {
                ViewBag.message = contact.Count + " adet öğe listelenmiştir";

            }
            else
            {
                ViewBag.message = "Listelenecek öğe bulunamadı";

            }
            return View(contact);

        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(ContactInformation cnc)
        {
            var category = db.ContactInformations.Where(x => x.Email == cnc.Email && !x.DeletionStatüs).FirstOrDefault();
            if (category != null)
            {
                ViewBag.message = "Sistemde Aynı Mail Mevcuttur";
                return View();
            }
            else
            {
                
                    cnc.CreatedTime = DateTime.Now;
                    cnc.UpdatedTime = DateTime.Now;
                    cnc.DeletionStatüs = false;
                    db.ContactInformations.Add(cnc);

                    if (cnc != null)
                    {
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.message = "Bir Hata Oluştu Lütfen Tekrar Deneyiniz";
                        return View();
                    }
           

            }

        }

        public ActionResult Delete(int id)
        {
            var del = db.ContactInformations.Find(id);
            del.DeletionStatüs = true;
            db.SaveChanges();
            return RedirectToAction("Index");


        }

        public ActionResult Update(int id)
        {
            var upd = db.ContactInformations.Find(id);

            return View(upd);
        }

        [HttpPost]
        public ActionResult Update(ContactInformation cnc)
        {

            var upd = db.ContactInformations.Find(cnc.Id);
            upd.Country = cnc.Country;
            upd.City = cnc.City;
            upd.Adress = cnc.Adress;
            upd.Email = cnc.Email;
            upd.Phone = cnc.Phone;
            upd.MapUrl = cnc.MapUrl;
            upd.UpdatedTime = DateTime.Now;

            var contact = db.ContactInformations.Where(x => x.Email == cnc.Email && !x.DeletionStatüs);

            if (contact.Count() > 1)
            {
                ViewBag.message = "Sistemde Aynı Mail Mevcuttur";
                return View();
            }
            else
            {
                

                if (cnc != null)
                {
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.message = "Bir Hata Oluştu Lütfen Tekrar Deneyiniz";
                    return View();
                }
            }



        }
    }
}

WebUILayer/Views/ContactInformation/Add.cshtml
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="card">
    <div class="card-header d-flex justify-content-between">
        <div class="header-title">
            <h4 class="card-title">İletişim Bilgisi Ekleme Sayfası</h4>
        </div>
    </div>
    <div class="card-body">

        @using (Html.BeginForm("Add", "ContactInformation", FormMethod.Post))
        {
            <div class="form-group">
                <label for="category-product">Ülke</label>
                <input type="text" class="form-control" name="Country" required="" id="category-product">

            </div>
            <div class="form-group">
                <label for="category-product">Şehir</label>
                <input type="text" class="form-control" name="City" required="" id="category-product">
            </div>

            <div class="form-group">
                <label for="category-product">Adres</label>

                <textarea class="form-control" name="Adress" required="" id="category-product"></textarea>
            </div>

            <div class="form-group">
                <label for="category-product">Email</label>
                <input type="email" class="form-control" name="Email" required="" id="category-product">
            </div>

            <div class="form-group">
                <label for="category-product">Telefon</label>
                <input type="tel" class="form-control" name="Phone" required="" id="category-product">
            </div>

            <div class="form-group">
                <label for="category-product">Harita Kodu</label>

                <textarea class="form-control" name="MapUrl" required="" id="category-product"></textarea>
            </div>

            <button type="submit" class="btn btn-primary">İletişim Bilgisi Ekle</button>

        }
    </div>
</div>




@if (ViewBag.message != null)
{
    <div class="swal2-container swal2-center swal2-backdrop-show" id="show-alert" style="overflow-y: auto;">
        <div aria-labelledby="swal2-title" aria-describedby="swal2-content" class="swal2-popup swal2-modal swal2-icon-error swal2-show" tabindex="-1" role="dialog" aria-live="assertive" aria-modal="true" style="display: flex;">
            <div class="swal2-header">
                <ul class="swal2-progress-steps" style="display: none;"></ul><div class="swal2-icon swal2-error swal2-icon-show" style="display: flex;">
                    <span class="swal2-x-mark">
                        <span class="swal2-x-mark-line-left"></span>
                        <span class="swal2-x-mark-line-right"></span>
                    </span>
                </div><div class="swal2-icon swal2-question" style="display: none;"></div><div class="swal2-icon swal2-warning" style="display: none;"></div><div class="swal2-icon swal2-info" style="display: none;"></div><div class="swal2-icon swal2-success" style="display: none;"></div><img class="swal2-image" style="display: none;"><h2 class="swal2-title" id="swal2-title" style="display: flex;">OOps!!</h2><button type="button" class="swal2-close" aria-label="Close this dialog" style="display: none;">×</button>
            </div><div class="swal2-content"><div id="swal2-content" class="swal2-html-container" style="display: block;">@ViewBag.message</div><input class="swal2-input" style="display: none;"><input type="file" class="swal2-file" style="display: none;"><div class="swal2-range" style="display: none;"><input type="range"><output></output></div><select class="swal2-select" style="display: none;"></select><div class="swal2-radio" style="display: none;"></div><label for="swal2-checkbox" class="swal2-checkbox" style="display: none;"><input type="checkbox"><span class="swal2-label"></span></label><textarea class="swal2-textarea" style="display: none;"></textarea><div class="swal2-validation-message" id="swal2-validation-message"></div></div><div class="swal2-actions" style="display: none;"><div class="swal2-loader"></div><button type="button" class="swal2-confirm swal2-styled" aria-label="" style="display: none;">OK</button><button type="button" class="swal2-deny swal2-styled" aria-label="" style="display: none;">No</button><button type="button" class="swal2-cancel swal2-styled" aria-label="" style="display: none;">Cancel</button></div><div class="swal2-footer" style="display: none;"></div><div class="swal2-timer-progress-bar-container"><div class="swal2-timer-progress-bar" style="display: none;"></div></div>
        </div>
    </div>
}

<script>
        var alert = document.querySelector("#show-alert");
        setTimeout(() => {
            alert.remove();
        }, 2000);
</script>

WebUILayer/Views/ContactInformation/Index.cshtml
@using EntityLayer.Entity
@model List<ContactInformation>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="card">
    <div class="card-header d-flex justify-content-between">
        <div class="header-title">
            <h4 class="card-title">@ViewBag.message</h4>
        </div>
    </div>
    <div class="card-body">

        <div class="table-responsive">
            <table id="datatable" class="table data-table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Ülke</th>
                        <th>Şehir</th>
                        <th>Adres</th>
                        <th>Email</th>
                        <th>Telefon</th>
                        <th>Eklenme Tarihi</th>
                        <th>Güncellenme Tarihi</th>



                        <th>İşlemler</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {

                        <tr>


                            <td>@item.Country</td>
                            <td>@item.City</td>
                            <td>@item.Adress</td>
                            <td>@item.Email</td>
                            <td>@item.Phone</td>
                           
                            <td>@item.CreatedTime.ToString("f")</td>
                            <td>@item.UpdatedTime.ToString("f")</td>



                            <td>
                                <div class="dropdown">
                                    <span class="dropdown-toggle1" id="dropdownMenuButton8" data-toggle="dropdown">
                                        <i class="ri-more-2-fill"></i>
                                    </span>
                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton8" style="">
                                        <a class="dropdown-item" href="#"><i class="ri-eye-fill mr-2"></i>View</a>
                                        <a class="dropdown-item" href="/ContactInformation/Delete/@item.Id" onclick="return confirm('Silmek istediğinize emin misiniz?')"><i class="ri-delete-bin-6-fill mr-2"></i>Sil</a>
                                        <a class="dropdown-item" href="/ContactInformation/Update/@item.Id"><i class="ri-pencil-fill mr-2"></i>Güncelle</a>
                                        <a class="dropdown-item" href="#"><i class="ri-printer-fill mr-2"></i>Print</a>
                                        <a class="dropdown-item" href="#"><i class="ri-file-download-fill mr-2"></i>Download</a>
                                    </div>
                                </div>

                            </td>

                        </tr>
                    }

                </tbody>

            </table>
        </div>
    </div>
</div>




<a href="/ContactInformation/Add/" class="btn btn-outline-dark rounded-pill mt-2"><i class="ri-add-line"></i>İletişim Bilgisi Ekle</a>

WebUILayer/Views/ContactInformation/Update.cshtml
@model EntityLayer.Entity.ContactInformation
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="card">
    <div class="card-header d-flex justify-content-between">
        <div class="header-title">
            <h4 class="card-title">İletişim Bilgi Güncelleme Sayfası</h4>
        </div>
    </div>
    <div class="card-body">

        @using (Html.BeginForm("Update", "ContactInformation", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(x => x.Id, new { @class = "form-control" })
            <div class="form-group">
                <label for="category-product">Ülke</label>
                @Html.TextBoxFor(x => x.Country, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label for="category-product">Şehir</label>
                @Html.TextBoxFor(x => x.City, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label for="category-product">Adres</label>
                @Html.TextAreaFor(x => x.Adress, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label for="category-product">Mail</label>
                @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label for="category-product">Telefon</label>
                @Html.TextBoxFor(x => x.Phone, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label for="category-product">Harita Kodu</label>
                @Html.TextAreaFor(x => x.MapUrl, new { @class = "form-control" })
            </div>

            <button type="submit" class="btn btn-primary">İletişim Bilgi Güncelle</button>

        }
    </div>
</div>




@if (ViewBag.message != null)
{
    <div class="swal2-container swal2-center swal2-backdrop-show" id="show-alert" style="overflow-y: auto;">
        <div aria-labelledby="swal2-title" aria-describedby="swal2-content" class="swal2-popup swal2-modal swal2-icon-error swal2-show" tabindex="-1" role="dialog" aria-live="assertive" aria-modal="true" style="display: flex;">
            <div class="swal2-header">
                <ul class="swal2-progress-steps" style="display: none;"></ul><div class="swal2-icon swal2-error swal2-icon-show" style="display: flex;">
                    <span class="swal2-x-mark">
                        <span class="swal2-x-mark-line-left"></span>
                        <span class="swal2-x-mark-line-right"></span>
                    </span>
                </div><div class="swal2-icon swal2-question" style="display: none;"></div><div class="swal2-icon swal2-warning" style="display: none;"></div><div class="swal2-icon swal2-info" style="display: none;"></div><div class="swal2-icon swal2-success" style="display: none;"></div><img class="swal2-image" style="display: none;"><h2 class="swal2-title" id="swal2-title" style="display: flex;">OOps!!</h2><button type="button" class="swal2-close" aria-label="Close this dialog" style="display: none;">×</button>
            </div><div class="swal2-content"><div id="swal2-content" class="swal2-html-container" style="display: block;">@ViewBag.message</div><input class="swal2-input" style="display: none;"><input type="file" class="swal2-file" style="display: none;"><div class="swal2-range" style="display: none;"><input type="range"><output></output></div><select class="swal2-select" style="display: none;"></select><div class="swal2-radio" style="display: none;"></div><label for="swal2-checkbox" class="swal2-checkbox" style="display: none;"><input type="checkbox"><span class="swal2-label"></span></label><textarea class="swal2-textarea" style="display: none;"></textarea><div class="swal2-validation-message" id="swal2-validation-message"></div></div><div class="swal2-actions" style="display: none;"><div class="swal2-loader"></div><button type="button" class="swal2-confirm swal2-styled" aria-label="" style="display: none;">OK</button><button type="button" class="swal2-deny swal2-styled" aria-label="" style="display: none;">No</button><button type="button" class="swal2-cancel swal2-styled" aria-label="" style="display: none;">Cancel</button></div><div class="swal2-footer" style="display: none;"></div><div class="swal2-timer-progress-bar-container"><div class="swal2-timer-progress-bar" style="display: none;"></div></div>
        </div>
    </div>
}

<script>
        var alert = document.querySelector("#show-alert");
        setTimeout(() => {
            alert.remove();
        }, 2000);
</script>