WebUILayer/Controllers/ProductBrandController.cs
using EntityLayer.Entity;
using EntityLayer.Modal;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUILayer.Controllers
{
    public class ProductBrandController : Controller
    {

        // GET: ProductCategory
        SystemContext db = new SystemContext();

        
        public ActionResult Index()
        {
            var brand = db.ProductBrands.Where(x => !x.DeletionStatüs).ToList();
            if (brand.Count != 0)
            {
                ViewBag.message = brand.Count + " adet marka listelenmiştir";

            }
            else
            {
                ViewBag.message = "Listelenecek öğe bulunamadı";

            }
            return View(brand);

        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(ProductBrand brd,HttpPostedFileBase File)
        {
            var brand = db.ProductBrands.Where(x => x.Title == brd.Title && !x.DeletionStatüs).FirstOrDefault();
           
            if (brand != null)
            {
                ViewBag.message = "Sistemde aynı marka mevcuttur";
                return View();
            }
            else
            {
                if (File != null)
                {

                    string photoName = Path.GetFileName(File.FileName);
                    string url = "/File/Brand/" + photoName;
                    File.SaveAs(Server.MapPath(url));
                   
                    brd.ImageUrl = url;
                    brd.CreatedTime = DateTime.Now;
                    brd.UpdatedTime = DateTime.Now;
                    brd.DeletionStatüs = false;
                    db.ProductBrands.Add(brd);

                    if (brd != null)
                    {
                        db.SaveChanges();
                        return RedirectToAction("Index");

                    }
                    else
                    {
                        ViewBag.message = "Bir Hata Oluştu Lütfen Tekrar Deneyiniz";
                        return View();
                    }

                }
                else
                {
                    ViewBag.message = "Resim Yüklenemedi Lütfen Tekrar Deneyiniz";
                    return View();

                }





            }

        }

        public ActionResult Delete(int id)
        {
            var del = db.ProductBrands.Find(id);
            del.DeletionStatüs = true;

            db.SaveChanges();
            return RedirectToAction("Index");


        }

        public ActionResult Update(int id)
        {
            var upd = db.ProductBrands.Find(id);

            return View(upd);
        }

        [HttpPost]
        public ActionResult Update(ProductBrand brd,HttpPostedFileBase File)
        {
            var a = brd.ImageUrl;
            var upd = db.ProductBrands.Find(brd.Id);
            upd.Title = brd.Title;
            upd.UpdatedTime = DateTime.Now;
            //var brand = db.ProductBrands.Where(x => x.Title == brd.Title && !x.DeletionStatüs).FirstOrDefault();
            var brand = db.ProductBrands.Where(x => x.Title == brd.Title && !x.DeletionStatüs);
            if (brand.Count()>1)
            {
                ViewBag.message = "Sistemde aynı marka mevcuttur";
                return View();
            }
            else
            {
                if (ModelState.IsValid)
                {
                    if (File != null)
                    {
                        string photoName = Path.GetFileName(File.FileName);
                        string url = "/File/Brand/" + photoName;
                        File.SaveAs(Server.MapPath(url));
                        upd.ImageUrl = url;
                    }
                }

            

                if (brd != null)
                {
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.message = "Bir Hata Oluştu Lütfen Tekrar Deneyiniz";
                    return View();
                }
            }


          

        }

        public ActionResult View(int id)
        {
            var product = db.Products.Where(x => !x.DeletionStatüs && x.ProductBrandId == id).ToList();
            if (product.Count != 0)
            {
                ViewBag.message = product.Count + " adet ürün listelenmiştir";

            }
            else
            {
                ViewBag.message = "Listelenecek öğe bulunamadı";

            }
            return View(product);

        }
    }
}

WebUILayer/Views/ProductBrand/Add.cshtml
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}




<div class="card">
    <div class="card-header d-flex justify-content-between">
        <div class="header-title">
            <h4 class="card-title">Marka Ekleme Sayfası</h4>
        </div>
    </div>
    <div class="card-body">

        @using (Html.BeginForm("Add", "ProductBrand", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="form-group">
                <label for="category-product">Marka Adı</label>
                <input type="text" class="form-control" name="Title" required="" id="category-product">
            </div>

            <div class="form-group">
                <div class="custom-file">

                    <input type="file" name="File" class="custom-file-input" id="customFile">
                    <label class="custom-file-label"  for="customFile">Lütfen Bir Resim Seçin...</label>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Marka Ekle</button>

        }
    </div>
</div>




@if (ViewBag.message != null)
{
    <div class="swal2-container swal2-center swal2-backdrop-show" id="show-alert" style="overflow-y: auto;">
        <div aria-labelledby="swal2-title" aria-describedby="swal2-content" class="swal2-popup swal2-modal swal2-icon-error swal2-show" tabindex="-1" role="dialog" aria-live="assertive" aria-modal="true" style="display: flex;">
            <div class="swal2-header">
                <ul class="swal2-progress-steps" style="display: none;"></ul><div class="swal2-icon swal2-error swal2-icon-show" style="display: flex;">
                    <span class="swal2-x-mark">
                        <span class="swal2-x-mark-line-left"></span>
                        <span class="swal2-x-mark-line-right"></span>
                    </span>
                </div><div class="swal2-icon swal2-question" style="display: none;"></div><div class="swal2-icon swal2-warning" style="display: none;"></div><div class="swal2-icon swal2-info" style="display: none;"></div><div class="swal2-icon swal2-success" style="display: none;"></div><img class="swal2-image" style="display: none;"><h2 class="swal2-title" id="swal2-title" style="display: flex;">OOps!!</h2><button type="button" class="swal2-close" aria-label="Close this dialog" style="display: none;">×</button>
            </div><div class="swal2-content"><div id="swal2-content" class="swal2-html-container" style="display: block;">@ViewBag.message</div><input class="swal2-input" style="display: none;"><input type="file" class="swal2-file" style="display: none;"><div class="swal2-range" style="display: none;"><input type="range"><output></output></div><select class="swal2-select" style="display: none;"></select><div class="swal2-radio" style="display: none;"></div><label for="swal2-checkbox" class="swal2-checkbox" style="display: none;"><input type="checkbox"><span class="swal2-label"></span></label><textarea class="swal2-textarea" style="display: none;"></textarea><div class="swal2-validation-message" id="swal2-validation-message"></div></div><div class="swal2-actions" style="display: none;"><div class="swal2-loader"></div><button type="button" class="swal2-confirm swal2-styled" aria-label="" style="display: none;">OK</button><button type="button" class="swal2-deny swal2-styled" aria-label="" style="display: none;">No</button><button type="button" class="swal2-cancel swal2-styled" aria-label="" style="display: none;">Cancel</button></div><div class="swal2-footer" style="display: none;"></div><div class="swal2-timer-progress-bar-container"><div class="swal2-timer-progress-bar" style="display: none;"></div></div>
        </div>
    </div>
}

<script>
        var alert = document.querySelector("#show-alert");
        setTimeout(() => {
            alert.remove();
        }, 2000);
</script>

WebUILayer/Views/ProductBrand/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}




<div class="card">
    <div class="card-header d-flex justify-content-between">
        <div class="header-title">
            <h4 class="card-title">@ViewBag.message</h4>
        </div>
    </div>
    <div class="card-body">

        <div class="table-responsive">
            <table id="datatable" class="table data-table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Marka</th>
                        <th>Görsel</th>
                        <th>Eklenme Tarihi</th>
                        <th>Güncellenme Tarihi</th>
                        <th>İşlemler</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {

                        <tr>


                            <td>@item.Title</td>
                            <td><img src="@item.ImageUrl" alt="No Image" class="img-fluid rounded avatar-40 text-center"></td>
                            <td>@item.CreatedTime.ToString("f")</td>
                            <td>@item.UpdatedTime.ToString("f")</td>



                            <td>
                                <div class="dropdown">
                                    <span class="dropdown-toggle1" id="dropdownMenuButton8" data-toggle="dropdown">
                                        <i class="ri-more-2-fill"></i>
                                    </span>
                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton8" style="">
                                        <a class="dropdown-item" href="/ProductBrand/View/@item.Id"><i class="ri-eye-fill mr-2"></i>Ürünleri Gör</a>
                                        <a class="dropdown-item" href="/ProductBrand/Delete/@item.Id" onclick="return confirm('Silmek istediğinize emin misiniz?')"><i class="ri-delete-bin-6-fill mr-2"></i>Sil</a>
                                        <a class="dropdown-item" href="/ProductBrand/Update/@item.Id"><i class="ri-pencil-fill mr-2"></i>Güncelle</a>
                                        <a class="dropdown-item" href="#"><i class="ri-printer-fill mr-2"></i>Print</a>
                                        <a class="dropdown-item" href="#"><i class="ri-file-download-fill mr-2"></i>Download</a>
                                    </div>
                                </div>
                             
                            </td>

                        </tr>
                    }

                </tbody>

            </table>
        </div>
    </div>
</div>





<a href="/ProductBrand/Add/" class="btn btn-outline-dark rounded-pill mt-2"><i class="ri-add-line"></i>Marka Ekle</a>

WebUILayer/Views/ProductBrand/Update.cshtml
@model EntityLayer.Entity.ProductBrand
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}






<div class="card">
    <div class="card-header d-flex justify-content-between">
        <div class="header-title">
            <h4 class="card-title">Marka Güncelleme Sayfası</h4>
        </div>
    </div>
    <div class="card-body">

        @using (Html.BeginForm("Update", "ProductBrand", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(x => x.Id, new { @class = "form-control" })
            <div class="form-group">
                <label for="category-product">Marka Adı</label>
                @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <div class="custom-file">
                    <label>Kategori Görsel</label>
                    <input type="file" name="File" class="custom-file-input" id="customFile">
                    <label class="custom-file-label" name="File" for="customFile">Lütfen Bir Resim Seçin...</label>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Güncelle</button>

        }
    </div>
</div>



@if (ViewBag.message != null)
{
    <div class="swal2-container swal2-center swal2-backdrop-show" id="show-alert" style="overflow-y: auto;">
        <div aria-labelledby="swal2-title" aria-describedby="swal2-content" class="swal2-popup swal2-modal swal2-icon-error swal2-show" tabindex="-1" role="dialog" aria-live="assertive" aria-modal="true" style="display: flex;">
            <div class="swal2-header">
                <ul class="swal2-progress-steps" style="display: none;"></ul><div class="swal2-icon swal2-error swal2-icon-show" style="display: flex;">
                    <span class="swal2-x-mark">
                        <span class="swal2-x-mark-line-left"></span>
                        <span class="swal2-x-mark-line-right"></span>
                    </span>
                </div><div class="swal2-icon swal2-question" style="display: none;"></div><div class="swal2-icon swal2-warning" style="display: none;"></div><div class="swal2-icon swal2-info" style="display: none;"></div><div class="swal2-icon swal2-success" style="display: none;"></div><img class="swal2-image" style="display: none;"><h2 class="swal2-title" id="swal2-title" style="display: flex;">OOps!!</h2><button type="button" class="swal2-close" aria-label="Close this dialog" style="display: none;">×</button>
            </div><div class="swal2-content"><div id="swal2-content" class="swal2-html-container" style="display: block;">@ViewBag.message</div><input class="swal2-input" style="display: none;"><input type="file" class="swal2-file" style="display: none;"><div class="swal2-range" style="display: none;"><input type="range"><output></output></div><select class="swal2-select" style="display: none;"></select><div class="swal2-radio" style="display: none;"></div><label for="swal2-checkbox" class="swal2-checkbox" style="display: none;"><input type="checkbox"><span class="swal2-label"></span></label><textarea class="swal2-textarea" style="display: none;"></textarea><div class="swal2-validation-message" id="swal2-validation-message"></div></div><div class="swal2-actions" style="display: none;"><div class="swal2-loader"></div><button type="button" class="swal2-confirm swal2-styled" aria-label="" style="display: none;">OK</button><button type="button" class="swal2-deny swal2-styled" aria-label="" style="display: none;">No</button><button type="button" class="swal2-cancel swal2-styled" aria-label="" style="display: none;">Cancel</button></div><div class="swal2-footer" style="display: none;"></div><div class="swal2-timer-progress-bar-container"><div class="swal2-timer-progress-bar" style="display: none;"></div></div>
        </div>
    </div>
}

<script>
        var alert = document.querySelector("#show-alert");
        setTimeout(() => {
            alert.remove();
        }, 2000);
</script>

WebUILayer/Views/ProductBrand/View.cshtml
@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}




<div class="card">
    <div class="card-header d-flex justify-content-between">
        <div class="header-title">
            <h4 class="card-title">@ViewBag.message</h4>
        </div>
    </div>
    <div class="card-body">

        <div class="table-responsive">
            <table id="datatable" class="table data-table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Ürün Adı</th>
                        <th>Açıklama</th>
                        <th>Fiyat</th>
                        <th>Stok</th>
                        <th>Marka</th>
                        <th>Kategori</th>
                        <th>Eklenme Tarihi</th>
                        <th>Güncellenme Tarihi</th>
                        <th>İşlemler</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {

                        <tr>


                            <td>@item.Title</td>
                            <td>@item.Description</td>
                            <td>@item.Price</td>
                            <td>@item.Stock</td>
                            <td>@item.ProductBrandId</td>
                            <td>@item.ProductCategoryId</td>
                            @*<td><img src="@item.ImageUrl" alt="No Image" class="img-fluid rounded avatar-40 text-center"></td>*@
                            <td>@item.CreatedTime.ToString("f")</td>
                            <td>@item.UpdatedTime.ToString("f")</td>



                            <td>
                                <div class="dropdown">
                                    <span class="dropdown-toggle1" id="dropdownMenuButton8" data-toggle="dropdown">
                                        <i class="ri-more-2-fill"></i>
                                    </span>
                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton8" style="">
                                        <a class="dropdown-item" href="#"><i class="ri-eye-fill mr-2"></i>View</a>
                                        <a class="dropdown-item" href="/Product/Delete/@item.Id" onclick="return confirm('Silmek istediğinize emin misiniz?')"><i class="ri-delete-bin-6-fill mr-2"></i>Sil</a>
                                        <a class="dropdown-item" href="/Product/Update/@item.Id"><i class="ri-pencil-fill mr-2"></i>Güncelle</a>
                                        <a class="dropdown-item" href="#"><i class="ri-printer-fill mr-2"></i>Print</a>
                                        <a class="dropdown-item" href="#"><i class="ri-file-download-fill mr-2"></i>Download</a>
                                    </div>
                                </div>

                            </td>

                        </tr>
                    }

                </tbody>

            </table>
        </div>
    </div>
</div>